apiVersion: v1
kind: Secret
metadata:
  name: demo-ui-config
  namespace: REPLACE_WITH_NAMESPACE
  labels:
    app.kubernetes.io/part-of: agent-boundary-lab
    app.kubernetes.io/name: demo-ui
type: Opaque
stringData:
  DEMO_UI_TOKEN: REPLACE_WITH_DEMO_UI_TOKEN
