#############################################
# KEY VAULT — generated credentials
#
# Only two secrets live here, both generated by Terraform and never typed by a human: the
# diagnostic route's bearer token and the Postgres administrator password.
#
# NO DEMO DATA, NO PROMPTS, NO PAYLOADS. The demo runs on synthetic data and the tools
# carry no credentials of their own, so there is nothing else that belongs in a vault.
#############################################

resource "azurerm_key_vault" "main" {
  name                = local.keyvault_name
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "standard"

  rbac_authorization_enabled = true
  purge_protection_enabled   = false

  # Reachable from the operator's machine so `terraform apply` can write the two secrets
  # without a jumpbox. The private endpoint in private-endpoints.tf gives in-VNet
  # consumers a private path; this governs the public one.
  public_network_access_enabled = true

  network_acls {
    bypass         = "AzureServices"
    default_action = "Allow"
  }

  tags = local.common_tags
}

# The deployer writes the generated secrets during apply.
resource "azurerm_role_assignment" "current_user_kv_admin" {
  scope                = azurerm_key_vault.main.id
  role_definition_name = "Key Vault Administrator"
  principal_id         = data.azurerm_client_config.current.object_id
}

# The workflow app reads the Postgres password at runtime through workload identity, so
# no connection string is ever baked into a manifest or an image.
resource "azurerm_role_assignment" "workflow_kv_secrets_user" {
  scope                = azurerm_key_vault.main.id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azurerm_user_assigned_identity.workflow.principal_id
}

resource "azurerm_key_vault_secret" "diagnostics_token" {
  name         = "diagnostics-token"
  value        = random_password.diagnostics_token.result
  key_vault_id = azurerm_key_vault.main.id

  depends_on = [azurerm_role_assignment.current_user_kv_admin]
}

resource "azurerm_key_vault_secret" "postgres_admin_password" {
  name         = "postgres-admin-password"
  value        = random_password.postgres_admin.result
  key_vault_id = azurerm_key_vault.main.id

  depends_on = [azurerm_role_assignment.current_user_kv_admin]
}
